### ISSUE TITLE
$drawn command, $saveconfig command, & friend color for nametags

### ISSUE THREAD

**Issue by 22s** [BleachDrinker420/bleachhack-1.14#108]

**Comment by BleachDrinker420** [comment]
what is $drawn? and why would you need $saveconfig when it automatically saves the config?

**Comment by 22s** [comment]
I believe the configs rollback if the game crashes, drawn would unlist modules in the array list, also you can’t unbind the default binded  modules to none anymore they rollback when you restart the game
