### ISSUE TITLE
fastbow

### ISSUE THREAD

**Issue by 22s** [BleachDrinker420/bleachhack-1.14#116]
fastb0w

**Comment by ayunami2000** [comment]
fastbow was patched server side a long time ago (when item usage cooldowns were added), so the only possibility i guess is if the server is actually <=1.8.9 but uses viaversion and then bleachhack can send fastbow packets and maybe itll work? idk

**Comment by 22s** [comment]
no fastbow as in autorelease

**Comment by BleachDrinker420** [comment]
Has been there for like a year under bowbot
