### ISSUE TITLE
sign up for github actions noob

### ISSUE THREAD

**Issue by d1gress** [BleachDrinker420/bleachhack-1.14#12]
autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild

**Comment by BleachDrinker420** [comment]
autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild autobuild

**Comment by BleachDrinker420** [comment]
![boomer](https://user-images.githubusercontent.com/36450388/67105860-e25d5a00-f1c9-11e9-8ac5-19aa1f0d6ccf.png)
