### ISSUE TITLE
Add a command to say words that start with the command prefix

### ISSUE THREAD

**Issue by feliscatusmeows** [BleachDrinker420/bleachhack-1.14#140]
Add a command similar to $say in other clients that allows you to put things that start with $ into chat.

**Comment by TheAirBlow** [comment]
what do you need exactly dude?

just print plain text into chat or simulate someone other print an message? Or other?

**Comment by I-can-have-a-long-username-if-I-want-to** [comment]
Some people might need to say things like $100 for that thing and I think adding a $say command will make it possible to say that.

**Comment by TheAirBlow** [comment]
Check out ChatTweaks, or idk how it called, but it have function to allow
print forbidden messaged, or you need something other?


пн, 31 авг. 2020 г., 21:31 I-can-have-a-long-username-if-I-want-to <
notifications@github.com>:

**Comment by BleachDrinker420** [comment]
just set the chat prefix to something else
*$prefix _* or something

**Comment by BleachDrinker420** [comment]
Added
