### ISSUE TITLE
notebot issue

### ISSUE THREAD

**Issue by TheAirBlow** [BleachDrinker420/bleachhack-1.14#147]
make notebot play on background
when window closes it stops playing

and make minimize button be like minimize button not like close button

**Comment by BleachDrinker420** [comment]
the notebot play thing only plays how the song sounds, you need noteblocks to actually play it, and the minimize button would do exactly the same thing as the close button

**Comment by TheAirBlow** [comment]
Dude, i mean, make it play in background...
