### ISSUE TITLE
question

### ISSUE THREAD

**Issue by TheAirBlow** [BleachDrinker420/bleachhack-1.14#149]
i am editing the source code and id needed 1.16.1

how I can change version fully from 1.16.2 to 1.12.1?

i tried to change configs, but it always crashes

**Comment by BleachDrinker420** [comment]
you'd need to change quite a lot to make it work on 1.16.1, the best option is probably just to use B14.1, its only 2 days older than the newest release https://github.com/BleachDrinker420/bleachhack-1.14/releases/download/B14.1/bleachhack-1.16.1-safe.jar

**Comment by TheAirBlow** [comment]
this is compiled jar

**Comment by TheAirBlow** [comment]
i need grandlew project

**Comment by BleachDrinker420** [comment]
there isn't a 1.16.1 project

**Comment by TheAirBlow** [comment]
bruh

**Comment by TheAirBlow** [comment]
lol i just downloaded source code of B14.1 and it's 1.16.1

**Comment by TheAirBlow** [comment]
why
```
Execution failed for task ':genSources'.
> java.nio.file.ClosedFileSystemException (no error message)
```

**Comment by TheAirBlow** [comment]
https://scans.gradle.com/s/4674oi27634no

**Comment by BleachDrinker420** [comment]
idk, i don't know how to gradle, just try it again maybe

**Comment by TheAirBlow** [comment]
already

**Comment by TheAirBlow** [comment]
I trying older version with 1.16.1 build

**Comment by TheAirBlow** [comment]
...that not crashes for now

**Comment by TheAirBlow** [comment]
i'll wait

**Comment by TheAirBlow** [comment]
And it worked!

also how you make it do not crash if mixins fail?

**Comment by BleachDrinker420** [comment]
set the defaultRequire thing in mixins.bleachhack.json to 0
