### ISSUE TITLE
Add auto baby piglin dupe for 1.16.x

### ISSUE THREAD

**Issue by I-can-have-a-long-username-if-I-want-to** [BleachDrinker420/bleachhack-1.14#150]
Add a autoduper for [this](https://minecraft.gamepedia.com/Tutorials/Block_and_item_duplication#Baby_Piglin_Item_Dupe_.28Vanilla_1.16-1.16.2.29_.28Patched_in_Paper.29).

**Comment by BleachDrinker420** [comment]
i knew about that dupe before the video but i didn't do anything about it because its like the endcrystal.me portal dupe except it only dupes 1 stack of items, its more effort to create an autodupe than to just manually dupe
