### ISSUE TITLE
bug: changing the x/y of the UI module results in it only being able to go down to 39

### ISSUE THREAD

**Issue by Lxgacyy** [BleachDrinker420/bleachhack-1.14#151]
![image](https://user-images.githubusercontent.com/63509728/91532230-d422b300-e92f-11ea-9c87-7e8e9b55ca8c.png)

**Comment by BleachDrinker420** [comment]
pls no issues about peepearl bleachhack, i dont work on it, but you can use the scroll wheel to set it exactly
