### ISSUE TITLE
Scaffolding doesn't work when player's position Y == 256

### ISSUE THREAD

**Issue by DefaultO** [BleachDrinker420/bleachhack-1.14#154]
### First, pretty annoying Issue, I encountered in the past few weeks using Bleach.

**Describe the bug**

Scaffolding won't work when you stand above the build limit (256) while you actually aim to automate building a platform on height (255) which is below you and a still buildable height.

My guess is, that it is one of these two lines. I thought at first that the -0.85 is odd (since mc might be weirdly rounding up) and changed it to a -1.00, but it wasn't it. It should be an easy fix tho.

```java
                Vec3d placeVec = mc.player.getPos().add(0, -0.85, 0);
		Set<BlockPos> blocks = (mode == 0
				? new LinkedHashSet<>(Arrays.asList(new BlockPos(placeVec), new BlockPos(placeVec.add(range, 0, 0)), new BlockPos(placeVec.add(-range, 0, 0)),
						new BlockPos(placeVec.add(0, 0, range)), new BlockPos(placeVec.add(0, 0, -range))))
						: getSpiral(mode, new BlockPos(placeVec)));
```
_You can find those in 1.16.X > src > main > java > bleach.hack > module > mods > Scaffold.java | Line: 87_

**To Reproduce**

1. Create a new local player world. Preferable in creative mode.
2. Go to any Coordinate and start building up using the Scaffolding Module. Reach Y:255.
3. You will see that the first block (when you jump or get higher from 255 to 256) gets placed under you. Every other block you try to place on Y:256 beneath you will result in showing "Height limit for building is 256 blocks".

**Expected behavior**

Since Y:255 is still a buildable horizontal area, scaffolding should work when you stand on Y:256. Letting you create a platform of your desire that way.

**Screenshots**

![image](https://user-images.githubusercontent.com/42414542/91665828-ac327b80-eaf8-11ea-840f-93ceee400ab1.png)
![image](https://user-images.githubusercontent.com/42414542/91665867-f0258080-eaf8-11ea-8d1d-157ca5ff4616.png)

**Additional context**

I am in an infrastructure group on an anarchy server. Had gotten the task to help with the obsidian roof @ spawn. This is how I got wind of this Bug. I was 100% sure someone else had to have found this one already. But after checking the 7 pages of Issues, I didn't find any Issue that describes this one.

This might be the same for older Minecraft/Bleach Versions!!!

(Sorry dominikaaaa for having messed up something with my brave tabs. didn't mean to open an issue at your stuff. wouldn't have noticed if you didn't reply)

**Comment by BleachDrinker420** [comment]
the -0.85 is because when walking on chests/soul sand or any non full blocks it doesn't place a block 2 blocks under you, but ill look into it

**Comment by BleachDrinker420** [comment]
Fixed, should be in this build when its done building https://github.com/BleachDrinker420/bleachhack-1.14/actions/runs/232132737
