### ISSUE TITLE
you must know it

### ISSUE THREAD

**Issue by TheAirBlow** [BleachDrinker420/bleachhack-1.14#158]
https://github.com/TheAirBlow/lunarium

just sayin'

u must know about this dude! and read the ReadMe

so i will have zero problems about this or idk

**Comment by 22s** [comment]
tf?

**Comment by 22s** [comment]
is there even anything unique about this other than you renaming it and not properly forking it? LOL

**Comment by TheAirBlow** [comment]
i not forked it beacuse i will loose issues tab

**Comment by BleachDrinker420** [comment]
![Untitled](https://user-images.githubusercontent.com/36450388/91872271-f857fa00-ec77-11ea-9a0d-198509653e74.png)
