### ISSUE TITLE
Anti hunger allows multiple jumps and floaty physics / negates fall damage

### ISSUE THREAD

**Issue by ZacharyCHT** [BleachDrinker420/bleachhack-1.14#160]
On both modes of anti-hunger I can jump multiple times in the air and I don't seem to have as much friction as normal. 
I also take no fall damage.

[https://streamable.com/ezvn4r](url)

**Comment by BleachDrinker420** [comment]
those are just side effects, dont really care to fix it, but it makes it so you dont use hunger while walking/running
