### ISSUE TITLE
Chest esp causes arm to intersect with storage blocks

### ISSUE THREAD

**Issue by ZacharyCHT** [BleachDrinker420/bleachhack-1.14#161]
While chest esp is enabled my hand doesn't display correctly over enabled storage blocks. Picture linked

[https://cdn.discordapp.com/attachments/747028413016965213/750602244809949254/unknown.png](url)

**Comment by TheAirBlow** [comment]
why not full screenshot?

**Comment by ZacharyCHT** [comment]
irrelevant

**Comment by BleachDrinker420** [comment]
y
