### ISSUE TITLE
Does antichunkban even do anything lol

### ISSUE THREAD

**Issue by lowjector** [BleachDrinker420/bleachhack-1.14#163]

**Comment by Vonr** [comment]
https://github.com/BleachDrinker420/bleachhack-1.14/blob/34e411dc9fcfbe26400756e174df3c3bcd6c2c84/BleachHack-Fabric-1.16/src/main/java/bleach/hack/mixin/MixinPacketInflater.java#L47

https://github.com/BleachDrinker420/bleachhack-1.14/blob/34e411dc9fcfbe26400756e174df3c3bcd6c2c84/BleachHack-Fabric-1.16/src/main/java/bleach/hack/mixin/MixinClientConnection.java#L85

**Comment by MorganAnkan** [comment]
it makes so a player named "chunk" cannot ban you

**Comment by cyxl** [comment]
My bad @Vonr and @lowjector  I didn't look at the usages and also I said stuff that I wasn't sure was true. Rookie Mistake, have a good day. (:
