### ISSUE TITLE
License terms and README

### ISSUE THREAD

**Issue by fee1-dead** [BleachDrinker420/bleachhack-1.14#177]
GPLv3 does not require anyone who has derived their work from the licensed material to disclose their source, only when distributing the software they must provide the corresponding source (that means: Private use OK, selling the modified program with the source OK). They actually don't even have to use the same license (the licenses just need to be compatible (such as licensed under GPLv3 *or later*)).

Unless you want to restrict some of this, please change README, so it matches the license's terms.

**Comment by fee1-dead** [comment]
Where is the fix? Your terms aren't legal if it restricts rights of some usage, which is given by GPLv3.

**Comment by BleachDrinker420** [comment]
i'm dumb, readme should be better now
