### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Godwhitelight** [BleachDrinker420/bleachhack-1.14#180]
1. auto armor
2. better flight. i mean without the valocity
3. novoid
4. better scaffolding

**Comment by vamiko666** [comment]
So I t automatically  answered with ligma sitonma sugma etc.

**Comment by BleachDrinker420** [comment]
1. exists, Player > AutoArmor
2. turn on static mode in flight
3. cringe
4. scaffold is good
