### ISSUE TITLE
Textboxes are focused all at once in protocol editor

### ISSUE THREAD

**Issue by degeneratehyperbola** [BleachDrinker420/bleachhack-1.14#185]
![зображення](https://user-images.githubusercontent.com/65950527/111041595-91df4000-8441-11eb-82b5-d9d9903ad9a5.png)
By clicking one of them all the boxes get focused as shown on a screenshot. Can't edit textboxes individually.

My installed mods are:

- baritone standalone version
- lithium
- sodium
- hydrogen
- phosphor
- worldedit for fabric
- modmenu 1.16.8
- bleachhack obviously

**Comment by BleachDrinker420** [comment]
Fixed, but tbh protocol changer is kinda trash, i'll probably remove it and bake in multiconnect or something later
