### ISSUE TITLE
Cant start the client

### ISSUE THREAD

**Issue by DasDirt** [BleachDrinker420/bleachhack-1.14#38]
Log: https://pastebin.com/6Fim0aki

**Comment by BleachDrinker420** [comment]
what os are you using?
what java version are you using?
is jdk installed?

**Comment by DasDirt** [comment]
Windows
Java 8
yes
![image](https://user-images.githubusercontent.com/23104366/70862354-a7627300-1f3b-11ea-8f50-bb7aabf78d4c.png)

**Comment by dominikaaaa** [comment]
very good developer 11/10 response
