### ISSUE TITLE
How to use .rbook

### ISSUE THREAD

**Issue by Earthcomputer** [BleachDrinker420/bleachhack-1.14#41]
Hello i cant understand how to book dup can some1 explain plox

**Comment by hube12** [comment]
> Hello i cant understand how to book dup can some1 explain plox

Wait aren't you that guy that ruined 2b2t?
Earth something?

**Comment by BleachDrinker420** [comment]
only elite hackers are allowed to know how to use that

**Comment by Vonr** [comment]
earth. istg you made it in clientcommands. you know how to use it. im also the guy who "doxxed" you btw still sorry but stop making useless issues lmao.

**Comment by Vonr** [comment]
on another note if you really dont know the syntax just check the code

**Comment by Vonr** [comment]
on another another note why use this rbook when you can use clientcommands's

**Comment by Vonr** [comment]
rbook [pages] [start char] [end char] [chrs/page]

**Comment by cookiedragon234** [comment]
🤡

**Comment by Crystallinqq** [comment]
ooo ya
