### ISSUE TITLE
Issue with binds

### ISSUE THREAD

**Issue by ayunami2000** [BleachDrinker420/bleachhack-1.14#43]
so basically my mouse has some extra buttons like volume buttons and the play/pause button for music. Whenever i click any of them though it toggles all unbound hacks presumably because the bind id of -1 is sent whenever these buttons are pressed. The effect is not pleasant because then most hacks are suddenly toggled! Please fix, in the meantime im going to try setting them to -2 in the file.

**Comment by ayunami2000** [comment]
yes it did work when i set them to -2, and in the gui it says that they are all bound to "KEY-2" but it works so yay. But still needs to be fixed as this is not a long term solution

**Comment by BleachDrinker420** [comment]
hm yes, i actually though about it and was gonna set all of them to -2 a few days ago but i forgot, i'll do it now

**Comment by BleachDrinker420** [comment]
fixed
