### ISSUE TITLE
Crash when pressing quit game in bleachhack menu

### ISSUE THREAD

**Issue by ayunami2000** [BleachDrinker420/bleachhack-1.14#47]
idk if this is intentional to make the game close faster but it does crash every time i press the bleachhack menu's quit game button

**Comment by BleachDrinker420** [comment]
send logs

**Comment by ayunami2000** [comment]
nothing is logged sadly and the launcher's crash report thing is empty

**Comment by ayunami2000** [comment]
does it just do a basic kill process on minecraft? if so then the launcher might think that it crashed

**Comment by BleachDrinker420** [comment]
it uses the Minecraft.close() which should be safe but i checked and the normal menu uses another method so i'll change it to that and see if it fixes it

**Comment by ayunami2000** [comment]
k cool

**Comment by BleachDrinker420** [comment]
ok should be fixed now
