### ISSUE TITLE
Suggestion: Change freecam to accurately show inventories

### ISSUE THREAD

**Issue by bon55** [BleachDrinker420/bleachhack-1.14#48]
Using freecam on a donkey/llama and opening your inventory with E will show your own player inventory rather than the inventory of the chested donkey/llama that you are riding. this may be intentional as other clients have this issue, but it prevents the illegal stack dupe from being done solo on endcrystal.

**Comment by 22s** [comment]
it would be more effective to have a button in the donkey inventory to send a mob mount packet

**Comment by BleachDrinker420** [comment]
done and done
