### ISSUE TITLE
dispenser 32k and normal killaura ignores friends and still hits them

### ISSUE THREAD

**Issue by 22s** [BleachDrinker420/bleachhack-1.14#50]
pls add support for friends list to ignore attacking friends.

**Comment by BleachDrinker420** [comment]
i added friend support for dispenser 32k but normal killaura already had friend support?

**Comment by 22s** [comment]
Then I’m autistic I didn’t try it I just read on the commit it looked like it only implemented esp and tracer stuff for friending
