### ISSUE TITLE
antivelocity doesnt work

### ISSUE THREAD

**Issue by 22s** [BleachDrinker420/bleachhack-1.14#53]
no velocity is buggy, it seems to cancel knockback instead of set it to 0 so when taking knockback you bounce around, also sometimes it doesnt cancel altogether and you get sent flying by crystals.

**Comment by ayunami2000** [comment]
in the tooltip it says "If you take some damage, you don't move. **Maybe.**" so this is a known issue

**Comment by BleachDrinker420** [comment]
added explosion damage to novelocity, fixed
