### ISSUE TITLE
shulker preview options

### ISSUE THREAD

**Issue by 22s** [BleachDrinker420/bleachhack-1.14#54]
option to toggle showing item names and only show contents gui thingy

**Comment by BleachDrinker420** [comment]
what do you mean?

**Comment by BleachDrinker420** [comment]
i'm gonna add so that it doesn't show when somethings empty

**Comment by 22s** [comment]
![image](https://user-images.githubusercontent.com/58058658/87120912-7e3a6480-c236-11ea-8656-47431aa85cd9.png)
option to unrender dis thing

**Comment by ayunami2000** [comment]
on a side note, add support for barrels, dispensers, droppers, campfires, jukeboxes, brewing stands, furnaces, smokers, that other new furnace, and any other storage container.

**Comment by 22s** [comment]
Wat kinda crack ru smoking none of those are portable. Only shulkers can contain items

**Comment by BleachDrinker420** [comment]
there already is support for chests, dispensers, droppers, hoppers and shulkers, but i'll add support for furnaces

**Comment by BleachDrinker420** [comment]
they can contain items if they are from create with nbt

**Comment by ayunami2000** [comment]
yeah i use bleachhack on totalfreedom and kaboom which are creative freeop and creative anarchy servers where i like to manipulate nbt

**Comment by ayunami2000** [comment]
dont forget barrels

also jukeboxes and campfires (AND soul campfires) can both have items it turns out so those would be cool too, and brewing stands can as well

**Comment by BleachDrinker420** [comment]
added in the latest commit
