### ISSUE TITLE
freecam is faster moving forwards

### ISSUE THREAD

**Issue by ayunami2000** [BleachDrinker420/bleachhack-1.14#77]
idk why but im in creative and flying on the server and i just went to freecam and whenever i move forward (W) i move faster than when pressing any of the other buttons (ASD) while in freecam.

edit: this is on the latest version of bleachhack

**Comment by lawrencfgsdfg** [comment]
this is intended i believe, but still somewhat annoying.

**Comment by BleachDrinker420** [comment]
its intentional

**Comment by BleachDrinker420** [comment]
well, not really, but its how normal creative flight works, so unleas people really complain it ill stay that way
