### ISSUE TITLE
dont toggle hacks if using F3+key

### ISSUE THREAD

**Issue by ayunami2000** [BleachDrinker420/bleachhack-1.14#78]
to toggle chunk boundaries the keycode is F3+G but G is bound to fly for me. can u make it not toggle hacks if u are holding F3 and doing an F3 key combination?

**Comment by lasnikprogram** [comment]
Just use another keybind or modify the client's code. If this is very important you can ask me for help

**Comment by BleachDrinker420** [comment]
Fixed
