### ISSUE TITLE
Bug: BowBot doesn't shoot on Charge:1.0

### ISSUE THREAD

**Issue by konata2027** [BleachDrinker420/bleachhack-1.14#84]
Minecraft: 1.16.1
Bleach: bleachhack-b13.1-20w28a.jar

![2020-07-16-105618_1920x1080_scrot](https://user-images.githubusercontent.com/43317627/87643281-54f86780-c753-11ea-810b-a20cfc38f8c7.png)

Also it's looks like there is issue with naming on ClickGUI screen - I'm using 1.16, not 1.15

**Comment by BleachDrinker420** [comment]
The naming was already fixed in the dev builds, but bowbot as also fixed now
