### ISSUE TITLE
Bug: Settings reset on unproper shutdown

### ISSUE THREAD

**Issue by konata2027** [BleachDrinker420/bleachhack-1.14#85]
Files in .minecraft/bleach folder gets reset in case of PC power loss. Not sure, but also might happen on hard reboot.

OS: Ubuntu 18.04
Minecraft: 1.16.1
Bleach: bleachhack-b13.1-20w28a.jar

**Comment by BleachDrinker420** [comment]
Uhh, that shouldn't happen, the only thing i can think of is that it shuts off right when it saves the configs which i can't really do anything about

**Comment by konata2027** [comment]
Well, that happened to me a few times (power outage and config reset), not once, and I never had that issue with other mods. That's why I considered this is a bug, not a simple coincidence.

**Comment by konata2027** [comment]
Also I can't reproduce it. Not even sure that it is reproducible at all.

**Comment by BleachDrinker420** [comment]
ok it should be 100% fixed now
