### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by crematoriums** [BleachDrinker420/bleachhack-1.14#88]
Please for the love of all that is holy don't make the elytra fly go forwards by default.... It's so cancer... Oh also you probably get annoyed of hearing this but auto armour

**Comment by Squ1dboi** [comment]
Just change elytra settings before you use it monkey

**Comment by crematoriums** [comment]
> Just change elytra fly settings before you use it monkey

packet doesnt bypass on the server i play so what am i supposed to change

**Comment by BleachDrinker420** [comment]
Elytrafly fixed, and there is already a thread for autoarmor
