### ISSUE TITLE
B13.1 click gui is completely messed up

### ISSUE THREAD

**Issue by bossdragon** [BleachDrinker420/bleachhack-1.14#90]
[https://i.imgur.com/epna6iV.png](url)
I think the image speaks for itself but you literally cant see anything in the gui because it has been crushed into a tiny sliver. I've tried .guireset it didn't fix it.

**Comment by BleachDrinker420** [comment]
can you zip and send your .minecraft/bleach/ folder?

**Comment by BleachDrinker420** [comment]
ok too late, fixed?

**Comment by bossdragonde** [comment]
i did fix it you just have to delete the bleach folder
